version: '3.8'
services:
  traefik:
    image: 'traefik:v2.10'
    command:
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:8080'
    ports:
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
  backend:
    build:
      context: .
      dockerfile: ./infra/Dockerfile-backend
    init: true
    env_file:
      # must contain DATABASE_URL, JWT_SECRET
      - .env.backend
    environment:
      PORT: 5174
      FRANKFURTER_BASE_URL: https://api.frankfurter.app/
    expose:
      - 5174
    labels:
      traefik.enable: true
      traefik.http.routers.backend.rule: PathPrefix(`/api`)
      traefik.http.routers.backend.entrypoints: web
      traefik.http.routers.backend.middlewares: backend-stripprefix
      traefik.http.middlewares.backend-stripprefix.stripprefix.prefixes: /api
  frontend:
    build:
      context: .
      dockerfile: ./infra/Dockerfile-frontend
      labels:
        traefik.enable: true
        traefik.http.routers.frontend.rule: Host(`localhost`)
        traefik.http.routers.frontend.entrypoints: web
  postgresql:
    image: postgres:15.3-alpine
    env_file:
      # must contain POSTGRES_PASSWORD
      - .env.postgres
    volumes:
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql:
