# compose.dev.yml but with ports exposed for local development without a devcontainer
name: expenses-dev
services:
  postgres:
    extends:
      file: compose.dev.yml
      service: postgres
    ports:
      - "5432:5432"

  redis:
    extends:
      file: compose.dev.yml
      service: redis
    ports:
      - "6379:6379"

  frankfurter:
    extends:
      file: compose.dev.yml
      service: frankfurter
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5200:8080"

  mailpit:
    extends:
      file: compose.dev.yml
      service: mailpit
    ports:
      - "8025:8025" # web
      - "1025:1025" # smtp

volumes:
  postgresql:
