services:
  backend:
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    build:
      context: .
      dockerfile: ./infra/Dockerfile-backend
    init: true
    # TODO: centralise/autogenerate this
    # must contain DATABASE_URL, JWT_SECRET, VAPID_EMAIL, VAPID_PRIVATE_KEY, VAPID_PUBLIC_KEY, PUBLIC_ORIGIN, SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD
    # optional SENTRY_DSN
    env_file:
      - .env.backend
    environment:
      PORT: 5174
      FRANKFURTER_BASE_URL: https://api.frankfurter.app/
      REDIS_URL: redis://redis:6379/

  frontend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./infra/Dockerfile-frontend
    environment:
      API_BASE_URL: http://backend:5174/
    ports:
      - 3000:3000

  postgres:
    restart: unless-stopped
    image: postgres:18-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    # must contain POSTGRES_PASSWORD
    env_file:
      - .env.postgres
    volumes:
      - postgres:/var/lib/postgresql
  redis:
    restart: unless-stopped
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres:
