packages:
  - packages/*

allowBuilds:
  "@prisma/engines": true
  "@sentry-internal/node-cpu-profiler": true
  "@sentry/cli": true
  "@swc/core": true
  bcrypt: true
  cpu-features: true
  esbuild: true
  lefthook: true
  msgpackr-extract: true
  msw: true
  prisma: true
  protobufjs: true
  ssh2: false
  unrs-resolver: false

blockExoticSubdeps: true

engineStrict: true

patchedDependencies:
  sonner: patches/sonner.patch

saveExact: true

strictDepBuilds: true
