packages:
  - packages/*

allowBuilds:
  '@prisma/engines': true
  '@sentry/cli': true
  '@sentry/node-cpu-profiler': true
  cpu-features: true
  esbuild: true
  jotai-rolldown: true
  lefthook: true
  msgpackr-extract: true
  msw: true
  prisma: true
  protobufjs: true
  ssh2: false

engineStrict: true

patchedDependencies:
  rrule@2.8.1: patches/rrule@2.8.1.patch
  sonner: patches/sonner.patch

saveExact: true

minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@nihalgonsalves/*"
