FROM node:20-slim as builder

RUN mkdir -p /opt/app
WORKDIR /opt/app

COPY package.json .
COPY ./packages/frontend/package.json ./packages/frontend/
COPY ./packages/backend/package.json ./packages/backend/
COPY ./packages/shared/package.json ./packages/shared/
COPY yarn.lock .

RUN corepack enable
RUN yarn install --immutable && yarn cache clean

COPY ./tsconfig.json ./tsconfig.base.json ./
COPY ./packages/frontend/ ./packages/frontend/
COPY ./packages/backend/ ./packages/backend/
COPY ./packages/shared/ ./packages/shared/

RUN yarn fe build

FROM caddy:2.6-alpine

COPY ./infra/Caddyfile /etc/caddy/Caddyfile
COPY --from=builder /opt/app/packages/frontend/dist /var/www

