# NODE_VERSION
FROM node:24-slim AS builder

# "Pin versions in apt-get install"
# hadolint ignore=DL3008
RUN apt-get update -y && \
  apt-get install -y --no-install-recommends \
    ca-certificates openssl \
  && rm -rf /var/lib/apt/lists/*

ENV COREPACK_ENABLE_DOWNLOAD_PROMPT=0
RUN corepack enable

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN mkdir -p /opt/app
WORKDIR /opt/app

COPY package.json .
COPY ./packages/frontend/package.json ./packages/frontend/
COPY ./packages/backend/package.json ./packages/backend/
COPY ./packages/shared/package.json ./packages/shared/
COPY ./packages/e2e/package.json ./packages/e2e/
COPY ./pnpm-lock.yaml .
COPY ./pnpm-workspace.yaml .
COPY ./patches/ ./patches/

# hadolint ignore=DL3060
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

COPY ./tsconfig.json ./tsconfig.base.json ./
COPY ./packages/frontend/ ./packages/frontend/
COPY ./packages/backend/ ./packages/backend/
COPY ./packages/shared/ ./packages/shared/
COPY ./packages/e2e/ ./packages/e2e/

ARG VITE_ENV_NAME=production
ARG VITE_GIT_COMMIT_SHA
ARG VITE_SENTRY_DSN
ARG SENTRY_AUTH_TOKEN
ARG SENTRY_ORG
ARG SENTRY_PROJECT

ENV VITE_ENV_NAME=${VITE_ENV_NAME}
ENV VITE_GIT_COMMIT_SHA=${VITE_GIT_COMMIT_SHA}
ENV VITE_SENTRY_DSN=${VITE_SENTRY_DSN}
ENV SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
ENV SENTRY_ORG=${SENTRY_ORG}
ENV SENTRY_PROJECT=${SENTRY_PROJECT}

RUN pnpm fe build:vite

FROM caddy:2.8-alpine

COPY ./infra/Caddyfile /etc/caddy/Caddyfile
COPY --from=builder /opt/app/packages/frontend/dist /var/www

