FROM node:18-slim as builder

RUN apt-get update -y && \
  apt-get install -y \
    # for prisma
    openssl \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /opt/app
WORKDIR /opt/app

RUN mkdir -p ./packages/frontend/
RUN mkdir -p ./packages/backend/

ADD package.json .
ADD ./packages/frontend/package.json ./packages/frontend/
ADD ./packages/backend/package.json ./packages/backend/
ADD yarn.lock .

RUN yarn install --frozen-lockfile

ADD ./tsconfig.json ./tsconfig.base.json ./
ADD ./packages/frontend/ ./packages/frontend/
ADD ./packages/backend/ ./packages/backend/

RUN cd packages/backend && yarn prisma generate && yarn build

FROM node:18-slim

RUN apt-get update -y && \
  apt-get install -y \
    # for prisma
    openssl \
  && rm -rf /var/lib/apt/lists/*

COPY --from=builder /opt/app/packages/backend/dist /opt/app
WORKDIR /opt/app

# https://www.prisma.io/docs/concepts/components/prisma-client/module-bundlers
COPY --from=builder /opt/app/node_modules/.prisma/client/libquery_engine* ./
COPY --from=builder /opt/app/node_modules/.prisma/client/schema.prisma ./

RUN yarn install

ENV NODE_ENV=production

USER node

CMD ["node", "/opt/app/app.js"]
