FROM node:18-slim as builder

RUN mkdir -p /opt/app
WORKDIR /opt/app

RUN mkdir -p ./packages/frontend/
RUN mkdir -p ./packages/backend/

ADD package.json .
ADD ./packages/frontend/package.json ./packages/frontend/
ADD ./packages/backend/package.json ./packages/backend/
ADD yarn.lock .

RUN yarn install --frozen-lockfile

ADD ./tsconfig.json ./tsconfig.base.json ./
ADD ./packages/frontend/ ./packages/frontend/
ADD ./packages/backend/ ./packages/backend/

RUN yarn be build

FROM node:18-slim

COPY --from=builder /opt/app/packages/backend/dist /opt/app

ENV NODE_ENV=production

USER node

CMD ["node", "/opt/app/app.js"]
