/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as StatsImport } from "./routes/stats";
import { Route as SettingsImport } from "./routes/settings";
import { Route as AuthImport } from "./routes/_auth";
import { Route as IndexImport } from "./routes/index";
import { Route as SheetsIndexImport } from "./routes/sheets/index";
import { Route as GroupsIndexImport } from "./routes/groups/index";
import { Route as SheetsSheetIdImport } from "./routes/sheets/$sheetId";
import { Route as GroupsSheetIdImport } from "./routes/groups/$sheetId";
import { Route as AuthVerifyEmailImport } from "./routes/auth/verify-email";
import { Route as AuthSignUpImport } from "./routes/auth/sign-up";
import { Route as AuthSignInImport } from "./routes/auth/sign-in";
import { Route as AuthResetPasswordImport } from "./routes/auth/reset-password";
import { Route as SheetsSheetIdImportImport } from "./routes/sheets/$sheetId.import";

// Create/Update Routes

const StatsRoute = StatsImport.update({
  id: "/stats",
  path: "/stats",
  getParentRoute: () => rootRoute,
} as any);

const SettingsRoute = SettingsImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRoute,
} as any);

const AuthRoute = AuthImport.update({
  id: "/_auth",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const SheetsIndexRoute = SheetsIndexImport.update({
  id: "/sheets/",
  path: "/sheets/",
  getParentRoute: () => rootRoute,
} as any);

const GroupsIndexRoute = GroupsIndexImport.update({
  id: "/groups/",
  path: "/groups/",
  getParentRoute: () => rootRoute,
} as any);

const SheetsSheetIdRoute = SheetsSheetIdImport.update({
  id: "/sheets/$sheetId",
  path: "/sheets/$sheetId",
  getParentRoute: () => rootRoute,
} as any);

const GroupsSheetIdRoute = GroupsSheetIdImport.update({
  id: "/groups/$sheetId",
  path: "/groups/$sheetId",
  getParentRoute: () => rootRoute,
} as any);

const AuthVerifyEmailRoute = AuthVerifyEmailImport.update({
  id: "/auth/verify-email",
  path: "/auth/verify-email",
  getParentRoute: () => rootRoute,
} as any);

const AuthSignUpRoute = AuthSignUpImport.update({
  id: "/auth/sign-up",
  path: "/auth/sign-up",
  getParentRoute: () => rootRoute,
} as any);

const AuthSignInRoute = AuthSignInImport.update({
  id: "/auth/sign-in",
  path: "/auth/sign-in",
  getParentRoute: () => rootRoute,
} as any);

const AuthResetPasswordRoute = AuthResetPasswordImport.update({
  id: "/auth/reset-password",
  path: "/auth/reset-password",
  getParentRoute: () => rootRoute,
} as any);

const SheetsSheetIdImportRoute = SheetsSheetIdImportImport.update({
  id: "/import",
  path: "/import",
  getParentRoute: () => SheetsSheetIdRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthImport;
      parentRoute: typeof rootRoute;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsImport;
      parentRoute: typeof rootRoute;
    };
    "/stats": {
      id: "/stats";
      path: "/stats";
      fullPath: "/stats";
      preLoaderRoute: typeof StatsImport;
      parentRoute: typeof rootRoute;
    };
    "/auth/reset-password": {
      id: "/auth/reset-password";
      path: "/auth/reset-password";
      fullPath: "/auth/reset-password";
      preLoaderRoute: typeof AuthResetPasswordImport;
      parentRoute: typeof rootRoute;
    };
    "/auth/sign-in": {
      id: "/auth/sign-in";
      path: "/auth/sign-in";
      fullPath: "/auth/sign-in";
      preLoaderRoute: typeof AuthSignInImport;
      parentRoute: typeof rootRoute;
    };
    "/auth/sign-up": {
      id: "/auth/sign-up";
      path: "/auth/sign-up";
      fullPath: "/auth/sign-up";
      preLoaderRoute: typeof AuthSignUpImport;
      parentRoute: typeof rootRoute;
    };
    "/auth/verify-email": {
      id: "/auth/verify-email";
      path: "/auth/verify-email";
      fullPath: "/auth/verify-email";
      preLoaderRoute: typeof AuthVerifyEmailImport;
      parentRoute: typeof rootRoute;
    };
    "/groups/$sheetId": {
      id: "/groups/$sheetId";
      path: "/groups/$sheetId";
      fullPath: "/groups/$sheetId";
      preLoaderRoute: typeof GroupsSheetIdImport;
      parentRoute: typeof rootRoute;
    };
    "/sheets/$sheetId": {
      id: "/sheets/$sheetId";
      path: "/sheets/$sheetId";
      fullPath: "/sheets/$sheetId";
      preLoaderRoute: typeof SheetsSheetIdImport;
      parentRoute: typeof rootRoute;
    };
    "/groups/": {
      id: "/groups/";
      path: "/groups";
      fullPath: "/groups";
      preLoaderRoute: typeof GroupsIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/sheets/": {
      id: "/sheets/";
      path: "/sheets";
      fullPath: "/sheets";
      preLoaderRoute: typeof SheetsIndexImport;
      parentRoute: typeof rootRoute;
    };
    "/sheets/$sheetId/import": {
      id: "/sheets/$sheetId/import";
      path: "/import";
      fullPath: "/sheets/$sheetId/import";
      preLoaderRoute: typeof SheetsSheetIdImportImport;
      parentRoute: typeof SheetsSheetIdImport;
    };
  }
}

// Create and export the route tree

interface SheetsSheetIdRouteChildren {
  SheetsSheetIdImportRoute: typeof SheetsSheetIdImportRoute;
}

const SheetsSheetIdRouteChildren: SheetsSheetIdRouteChildren = {
  SheetsSheetIdImportRoute: SheetsSheetIdImportRoute,
};

const SheetsSheetIdRouteWithChildren = SheetsSheetIdRoute._addFileChildren(
  SheetsSheetIdRouteChildren,
);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "": typeof AuthRoute;
  "/settings": typeof SettingsRoute;
  "/stats": typeof StatsRoute;
  "/auth/reset-password": typeof AuthResetPasswordRoute;
  "/auth/sign-in": typeof AuthSignInRoute;
  "/auth/sign-up": typeof AuthSignUpRoute;
  "/auth/verify-email": typeof AuthVerifyEmailRoute;
  "/groups/$sheetId": typeof GroupsSheetIdRoute;
  "/sheets/$sheetId": typeof SheetsSheetIdRouteWithChildren;
  "/groups": typeof GroupsIndexRoute;
  "/sheets": typeof SheetsIndexRoute;
  "/sheets/$sheetId/import": typeof SheetsSheetIdImportRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "": typeof AuthRoute;
  "/settings": typeof SettingsRoute;
  "/stats": typeof StatsRoute;
  "/auth/reset-password": typeof AuthResetPasswordRoute;
  "/auth/sign-in": typeof AuthSignInRoute;
  "/auth/sign-up": typeof AuthSignUpRoute;
  "/auth/verify-email": typeof AuthVerifyEmailRoute;
  "/groups/$sheetId": typeof GroupsSheetIdRoute;
  "/sheets/$sheetId": typeof SheetsSheetIdRouteWithChildren;
  "/groups": typeof GroupsIndexRoute;
  "/sheets": typeof SheetsIndexRoute;
  "/sheets/$sheetId/import": typeof SheetsSheetIdImportRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/_auth": typeof AuthRoute;
  "/settings": typeof SettingsRoute;
  "/stats": typeof StatsRoute;
  "/auth/reset-password": typeof AuthResetPasswordRoute;
  "/auth/sign-in": typeof AuthSignInRoute;
  "/auth/sign-up": typeof AuthSignUpRoute;
  "/auth/verify-email": typeof AuthVerifyEmailRoute;
  "/groups/$sheetId": typeof GroupsSheetIdRoute;
  "/sheets/$sheetId": typeof SheetsSheetIdRouteWithChildren;
  "/groups/": typeof GroupsIndexRoute;
  "/sheets/": typeof SheetsIndexRoute;
  "/sheets/$sheetId/import": typeof SheetsSheetIdImportRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | ""
    | "/settings"
    | "/stats"
    | "/auth/reset-password"
    | "/auth/sign-in"
    | "/auth/sign-up"
    | "/auth/verify-email"
    | "/groups/$sheetId"
    | "/sheets/$sheetId"
    | "/groups"
    | "/sheets"
    | "/sheets/$sheetId/import";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | ""
    | "/settings"
    | "/stats"
    | "/auth/reset-password"
    | "/auth/sign-in"
    | "/auth/sign-up"
    | "/auth/verify-email"
    | "/groups/$sheetId"
    | "/sheets/$sheetId"
    | "/groups"
    | "/sheets"
    | "/sheets/$sheetId/import";
  id:
    | "__root__"
    | "/"
    | "/_auth"
    | "/settings"
    | "/stats"
    | "/auth/reset-password"
    | "/auth/sign-in"
    | "/auth/sign-up"
    | "/auth/verify-email"
    | "/groups/$sheetId"
    | "/sheets/$sheetId"
    | "/groups/"
    | "/sheets/"
    | "/sheets/$sheetId/import";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRoute: typeof AuthRoute;
  SettingsRoute: typeof SettingsRoute;
  StatsRoute: typeof StatsRoute;
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute;
  AuthSignInRoute: typeof AuthSignInRoute;
  AuthSignUpRoute: typeof AuthSignUpRoute;
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute;
  GroupsSheetIdRoute: typeof GroupsSheetIdRoute;
  SheetsSheetIdRoute: typeof SheetsSheetIdRouteWithChildren;
  GroupsIndexRoute: typeof GroupsIndexRoute;
  SheetsIndexRoute: typeof SheetsIndexRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  GroupsSheetIdRoute: GroupsSheetIdRoute,
  SheetsSheetIdRoute: SheetsSheetIdRouteWithChildren,
  GroupsIndexRoute: GroupsIndexRoute,
  SheetsIndexRoute: SheetsIndexRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/settings",
        "/stats",
        "/auth/reset-password",
        "/auth/sign-in",
        "/auth/sign-up",
        "/auth/verify-email",
        "/groups/$sheetId",
        "/sheets/$sheetId",
        "/groups/",
        "/sheets/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/stats": {
      "filePath": "stats.tsx"
    },
    "/auth/reset-password": {
      "filePath": "auth/reset-password.tsx"
    },
    "/auth/sign-in": {
      "filePath": "auth/sign-in.tsx"
    },
    "/auth/sign-up": {
      "filePath": "auth/sign-up.tsx"
    },
    "/auth/verify-email": {
      "filePath": "auth/verify-email.tsx"
    },
    "/groups/$sheetId": {
      "filePath": "groups/$sheetId.tsx"
    },
    "/sheets/$sheetId": {
      "filePath": "sheets/$sheetId.tsx",
      "children": [
        "/sheets/$sheetId/import"
      ]
    },
    "/groups/": {
      "filePath": "groups/index.tsx"
    },
    "/sheets/": {
      "filePath": "sheets/index.tsx"
    },
    "/sheets/$sheetId/import": {
      "filePath": "sheets/$sheetId.import.tsx",
      "parent": "/sheets/$sheetId"
    }
  }
}
ROUTE_MANIFEST_END */
