version: '3'
services:
  workspace:
    volumes:
      - .:/workspace:cached
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres
      REDIS_URL: redis://redis:6379
      FRANKFURTER_BASE_URL: http://frankfurter:8080/
    expose:
      - 5173
      - 5174
    command: /bin/sh -c "while sleep 1000; do :; done"
