http:
  middlewares:
    default-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        stsSeconds: 31536000 # 1 year
        stsIncludeSubdomains: false
        customResponseHeaders:
          document-policy: js-profiling
          # reporting-endpoints: csp-endpoint="https://....ingest.us.sentry.io/api/.../security/?sentry_key=..."
        contentSecurityPolicy: >
          default-src 'self';
          script-src 'self' blob:;
          style-src 'self' 'unsafe-inline';
          connect-src 'self' https://....ingest.sentry.io;
        # report-uri https://....ingest.us.sentry.io/api/.../security/?sentry_key=...;
        # report-to csp-endpoint
