http:
  middlewares:
    default-headers:
      headers:
        frameDeny: true
        contentTypeNosniff: true
        stsSeconds: 31536000 # 1 year
        stsIncludeSubdomains: false
        contentSecurityPolicy: >
          default-src 'self';
          worker-src 'self' blob:;
          child-src 'self' blob:;
          style-src 'self' 'unsafe-inline';
