name: playwright
on: [push]
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # waiting on: https://github.com/actions/setup-node/issues/531
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - run: yarn install --immutable
      - run: yarn be node bin/prepare-ci-e2e.mjs
      - run: yarn e2e prepare-pw

      - run: docker compose build --pull
      - run: docker compose up postgres --wait --detach
      - run: docker compose run --rm backend yarn prisma migrate deploy
      - run: docker compose up --detach

      - run: yarn e2e test
        env:
          PW_BASE_URL: http://localhost:8080

      - if: always()
        run: docker compose down --volumes

      - if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
